name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
    
    - name: Install dependencies
      run: pnpm install
    
    - name: Setup code signing (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        # Decode certificate
        echo "${{ secrets.CSC_LINK_BASE64 }}" | base64 --decode > certificate.p12
        
        # Create temporary keychain
        security create-keychain -p actions temp.keychain
        security default-keychain -s temp.keychain
        security unlock-keychain -p actions temp.keychain
        security set-keychain-settings -t 3600 -u temp.keychain
        
        # Import certificate
        security import certificate.p12 -k temp.keychain -P "${{ secrets.CSC_KEY_PASSWORD }}" -T /usr/bin/codesign -T /usr/bin/productsign
        security set-key-partition-list -S apple-tool:,apple: -s -k actions temp.keychain
        
        # Set environment variables
        echo "CSC_LINK=$PWD/certificate.p12" >> $GITHUB_ENV
        echo "CSC_KEY_PASSWORD=${{ secrets.CSC_KEY_PASSWORD }}" >> $GITHUB_ENV
        echo "APPLE_ID=${{ secrets.APPLE_ID }}" >> $GITHUB_ENV
        echo "APPLE_APP_SPECIFIC_PASSWORD=${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}" >> $GITHUB_ENV
        echo "APPLE_TEAM_ID=${{ secrets.APPLE_TEAM_ID }}" >> $GITHUB_ENV
        echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> $GITHUB_ENV
        echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> $GITHUB_ENV
        echo "DIST_GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> $GITHUB_ENV
        echo "DIST_GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> $GITHUB_ENV
    
    - name: Build app
      run: pnpm dist:mac
      if: matrix.os == 'macos-latest'
    
    - name: Build app
      run: pnpm dist:win
      if: matrix.os == 'windows-latest'
    
    - name: Build app
      run: pnpm dist:linux
      if: matrix.os == 'ubuntu-latest'
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dingo-track-${{ matrix.os }}
        path: dist-electron/

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    
    - name: Generate release metadata
      run: |
        VERSION=$(node -p "require('./package.json').version")
        BUILD_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        echo "{\"version\":\"$VERSION\",\"buildTime\":\"$BUILD_TIME\",\"releaseTag\":\"${{ github.ref_name }}\"}" > artifacts/release-info.json
        cat artifacts/release-info.json
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        draft: false
        prerelease: false
        generate_release_notes: true
        files: |
          artifacts/dingo-track-macos-latest/*.dmg
          artifacts/dingo-track-windows-latest/*.exe
          artifacts/dingo-track-ubuntu-latest/*.AppImage
          artifacts/release-info.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 