name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
    
    - name: Install dependencies
      run: pnpm install
    
    - name: Build app
      run: pnpm dist:mac
      if: matrix.os == 'macos-latest'
    
    - name: Build app
      run: pnpm dist:win
      if: matrix.os == 'windows-latest'
    
    - name: Build app
      run: pnpm dist:linux
      if: matrix.os == 'ubuntu-latest'
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dingo-track-${{ matrix.os }}
        path: dist-electron/ 